dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install numpy>=1.16
  - pip install -r requirements.txt
script:
  - pip install coverage
  - coverage run -m unittest
after_success:
  - pip install codecov
  - codecov