name: test build
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        environment: deployment
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

# Necessary action when needing to use AWS credentials.
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-west-1

          - name: Install Python
            uses: actions/setup-python@v3
            with:
              python-version: '3.7'

          - name: Install Dependencies
            run: | 
              sudo pip install -r requirements.txt
              sudo pip install awscli coverage

          - name: Setup Mosek License File
            run: |
              sudo mkdir /root/mosek
              mkdir $HOME/mosek
              aws s3 cp s3://slac.gismo.ci.artifacts/mosek.license/mosek.lic $HOME/mosek/mosek.lic
              sudo cp $HOME/mosek/mosek.lic /root/mosek/mosek.lic

# Current unit test is not consistent. Occasionally fails despite usually passing. Needs to be fixed.
          - name: Run Unit Tests
            run: sudo coverage run -m unittest

    deploy-pypi:
        needs: build
        runs-on: ubuntu-latest
        environment: deployment
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

          - name: Install Python
            uses: actions/setup-python@v3
            with:
              python-version: '3.7'

          - name: Install Twine
            run: sudo pip install twine

          - name: Create the distribution
            run: sudo python setup.py sdist bdist_wheel

          - name: Push to PyPI
            run: sudo twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} dist/*

    deploy-conda:
#        needs: build
        runs-on: ubuntu-latest
# sets default shell to remove need for source to run the conda shell
        defaults:
          run:
            shell: bash -l {0}
        environment: deployment
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

# Much better than manual installation, original version Miniconda2-4.7.10-Linux-x86_64.sh is broken
          - name: Install Miniconda
            uses: conda-incubator/setup-miniconda@v2
            with:
              auto-activate-base: true
              activate-environment: ""
              miniconda-version: "latest"

          - name: Install the Conda Dependencies
            run: | 
              conda config --set always_yes yes --set auto_update_conda false
              conda update conda
              conda install conda-build

# run install twice due to client-size to ensure all files downloaded
# echo yes before login to prevent anaconda bug breaking automation
          - name: Build the Anaconda Package
            id: condabuild
            run: |
              conda install anaconda-client
              conda install anaconda-client
              conda config --set anaconda_upload no
              echo yes | anaconda login --username ${{ secrets.ANACONDA_CLOUD_USERNAME }} --password ${{ secrets.ANACONDA_CLOUD_PASSWORD }}
              VERSION_FROM_GIT_TAG=$(`git tag --list 'v*[0-9]' --sort=version:refname | tail -1 | cut -c 2-`) conda build . -c conda-forge -c slacgismo --numpy 1.16.4
              echo "VERSION_FROM_GIT_TAG=$(`git tag --list 'v*[0-9]' --sort=version:refname | tail -1 | cut -c 2-`)"
              echo $VERSION_FROM_GIT_TAG
              echo ${{ env.VERSION_FROM_GIT_TAG }}
              echo "HMMMMM"
              echo "NEXT"
              echo "NEXT"
              echo "::set-output name=gitversionthree::$(git tag --list "v*[0-9]"" --sort=version:refname | tail -1 | cut -c 2-)"
              echo "::set-output name=gitversionfour::$(`git tag --list "v*[0-9]" --sort=version:refname | tail -1 | cut -c 2-`)"
              echo "${{ steps.condabuild.outputs.gitversion }}"
              echo "${{ steps.condabuild.outputs.gitversiontwo }}"
              echo "${{ steps.condabuild.outputs.gitversionthree }}"
              echo "${{ steps.condabuild.outputs.gitversionfour }}"
              anaconda upload -u slacgismo  /usr/share/miniconda3/conda-bld/noarch/solar-data-tools-$VERSION_FROM_GIT_TAG-*.tar.bz2