name: Test Deployment
on: 
  pull_request:
    branches:
      - master
    types: [opened]
jobs:
    deploy-pypi-test:
        runs-on: ubuntu-latest
        environment: test-deployment
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

          - name: Install Python
            uses: actions/setup-python@v3
            with:
              python-version: '3.7'

          - name: Install Twine
            run: sudo pip install twine

          - name: Create the distribution
            run: |
              git fetch --prune --unshallow --tags
              sudo python setup.py sdist bdist_wheel

          - name: Push to PyPI
            run: sudo twine upload -r testpypi -u ${{ secrets.PYPI_TEST_USERNAME }} -p ${{ secrets.PYPI_TEST_PASSWORD }} dist/*